on:
  push:
    branches: [feature/6-add-CI/CD-in-forgejo]

jobs:
  test:
    runs-on: docker # name of the runner
    container:
      image: forgejo.samxela.eu/flutter/flutter-test:12.6-slim
      credentials:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Flutter tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter test