name: Flutter run tests
run-name: ${{ github.actor }} is run tests
on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: samxela/flutter-test-sqlite:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Flutter tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter test