name: Flutter run tests
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.2
      - name: Install dependencies
        run: flutter pub get
      - name: Generate database files
        run: flutter pub run build_runner build
      - name: Run Flutter tests
        run: flutter test --machine > test-results.json
      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Flutter Tests
          path: test-results.json
          reporter: flutter-json
